using UnityEditor;
using UnityEditor.Compilation;
using UnityEngine;
using UnityEditor.Callbacks;
using System;
using System.IO;
using System.Linq;
using System.Text;

[InitializeOnLoad]
public static class NetHandlerAutoWatcher
{
    private static DateTime lastCheck = DateTime.MinValue;
    private const int CooldownSeconds = 3;  // 缩短到 3 秒，重命名场景需要快速响应
    private static bool isChecking = false;  // 防止 delayCall 重入

    static NetHandlerAutoWatcher()
    {
        EditorApplication.delayCall += TryCheckChange;
        CompilationPipeline.assemblyCompilationFinished += OnAssemblyCompilationFinished;
    }

    [DidReloadScripts]
    private static void OnReload()
    {
        EditorApplication.delayCall += TryCheckChange;
    }

    /// <summary>
    /// 关键修复 —— 打破"重命名死锁"：
    /// 死锁链条：源码改名 → TestSocket 编译成功 → NetHandlerGenerated.cs 引用旧名 → 编译失败 →
    ///           整个 assembly 不更新 → 反射拿旧名 → 跟旧 snapshot 一致 → "无变化" → 永远不重生成。
    /// 解决方案：检测到 NetHandlerGenerated.cs 自己报错时，主动用占位文件清空它，
    /// 让 TestSocket 编译先过；下一轮 DidReloadScripts 触发时 ScanHandlers 能拿到新方法名，
    /// 重新生成正确的 NetHandlerGenerated.cs。
    /// </summary>
    private static void OnAssemblyCompilationFinished(string assemblyPath, CompilerMessage[] messages)
    {
        if (messages == null || messages.Length == 0) return;

        var errors = messages.Where(m => m.type == CompilerMessageType.Error).ToList();
        if (errors.Count == 0) return;

        // 跨平台路径匹配：把 \ 转成 /，用 EndsWith 防止误匹配同名子串
        bool isGenFileError = errors.Any(m =>
            !string.IsNullOrEmpty(m.file) &&
            m.file.Replace('\\', '/').EndsWith("NetHandlerGenerated.cs", StringComparison.OrdinalIgnoreCase)
        );
        if (!isGenFileError) return;

        Debug.LogWarning($"[NetHandlerAutoWatcher] 检测到 NetHandlerGenerated.cs 编译失败（{errors.Count} 个错误）。通常是源码方法改名/删除导致。");
        Debug.LogWarning($"[NetHandlerAutoWatcher] 首个错误: {errors[0].file}({errors[0].line},{errors[0].column}) - {errors[0].message}");
        Debug.LogWarning($"[NetHandlerAutoWatcher] 主动清空 NetHandlerGenerated.cs 以打破死锁...");

        // 延迟一帧再清空，避免和 Unity 编译流程的内部锁冲突
        EditorApplication.delayCall += ClearGeneratedFile;
    }

    private static void ClearGeneratedFile()
    {
        try
        {
            if (!File.Exists(NetHandlerGeneratorUtil.GeneratedFile))
            {
                return;
            }

            var placeholder =
                "// ------------------------------------------------------------------------------\n" +
                "// <auto-generated-placeholder>\n" +
                "//     原内容已清空，因为引用了不存在的方法。\n" +
                "//     将在下次编译完成后由 NetHandlerAutoWatcher 自动重新生成。\n" +
                "// ------------------------------------------------------------------------------\n" +
                "using UnityEngine;\n" +
                "public static class NetHandlerGenerated\n" +
                "{\n" +
                "    public static void RegisterAll()\n" +
                "    {\n" +
                "        Debug.LogWarning(\"[NetHandlerGenerated] 当前为占位文件，handler 尚未注册，等待下次重新生成\");\n" +
                "    }\n" +
                "}\n";

            File.WriteAllText(NetHandlerGeneratorUtil.GeneratedFile, placeholder, new UTF8Encoding(false));
            AssetDatabase.Refresh();
            Debug.Log("[NetHandlerAutoWatcher] NetHandlerGenerated.cs 已清空，等待下次重新生成");
        }
        catch (Exception e)
        {
            Debug.LogError($"[NetHandlerAutoWatcher] 清空 NetHandlerGenerated.cs 失败: {e}");
        }
    }

    [MenuItem("Tools/Net/强制重新生成 Handler")]
    public static void ForceRegenerate()
    {
        if (EditorApplication.isCompiling || EditorApplication.isUpdating)
        {
            Debug.LogWarning("[NetHandlerAutoWatcher] 正在编译/更新中，请稍后再试。");
            return;
        }

        try
        {
            // 强制清空旧快照，让下一次扫描结果必然被采纳
            if (File.Exists(NetHandlerGeneratorUtil.SnapshotPath))
            {
                File.Delete(NetHandlerGeneratorUtil.SnapshotPath);
            }

            var current = NetHandlerGeneratorUtil.ScanHandlers();
            NetHandlerGeneratorUtil.SaveSnapshot(current);
            NetHandlerGeneratorUtil.GenerateCode(current);
            AssetDatabase.Refresh();
            Debug.Log($"[NetHandlerAutoWatcher] 强制重新生成完成（数量: {current.Count}）。");
        }
        catch (Exception e)
        {
            Debug.LogError($"[NetHandlerAutoWatcher] 强制重新生成失败: {e}");
        }
    }

    private static void TryCheckChange()
    {
        if (isChecking) return;
        if (EditorApplication.isCompiling || EditorApplication.isUpdating) return;
        if ((DateTime.Now - lastCheck).TotalSeconds < CooldownSeconds) return;

        isChecking = true;
        try
        {
            var current = NetHandlerGeneratorUtil.ScanHandlers();
            var old = NetHandlerGeneratorUtil.LoadSnapshot();
            bool changed = !old.SequenceEqual(current);

            if (!changed)
            {
                Debug.Log("[NetHandlerAutoWatcher] 无变化，无需重新生成。");
                lastCheck = DateTime.Now;
                return;
            }

            NetHandlerGeneratorUtil.GenerateCode(current);
            NetHandlerGeneratorUtil.SaveSnapshot(current);
            AssetDatabase.Refresh();
            lastCheck = DateTime.Now;

            Debug.Log($"[NetHandlerAutoWatcher] 检测到变化，已自动重建注册文件（数量: {current.Count}）。");
        }
        catch (Exception e)
        {
            // 失败时不要写快照、也不要更新 lastCheck —— 保持旧文件不动，下次可立即重试
            Debug.LogError($"[NetHandlerAutoWatcher] 运行错误（保持旧文件，下次重试）: {e}");
        }
        finally
        {
            isChecking = false;
        }
    }
}
